### ISSUE TITLE
Doesn't work with Hexo 3.0.1 

### ISSUE THREAD

**Issue by mniinio** [timnew/hexo-generator-atom-markdown-writer-meta#1]
Reference error: hexo is not defined

**Comment by timnew** [comment]
Sorry it doesn't support Hexo 3.x yet

**Comment by Edenharder** [comment]
Could you update it? Thanks!

**Comment by timnew** [comment]
Working on it. API changed so much, getting familiar with these new APIs

**Comment by wangray** [comment]
Does this support Hexo 3 yet?

**Comment by mh61503891** [comment]
I have written the [scripts/meta.json](https://gist.github.com/mh61503891/544d3c1eefd00b1012463b860222d34f) for temporary use on Hexo 3.

Create the file to `scripts/meta.js` and paste this script.

```meta.js
// See: https://github.com/zhuochun/md-writer/wiki/Settings-for-Front-Matters
// Path: scripts/meta.js
// Author: Masayuki Higashino
// License: MIT
hexo.extend.generator.register('meta', function(locals) {
  var meta = {
    tags: [],
    posts: [],
    categories: []
  }
  locals.tags.sort('name').each(function(tag) {
    meta.tags.push(tag.name)
  })
  locals.categories.sort('name').each(function(category) {
    meta.categories.push(category.name)
  })
  locals.posts.sort('name').each(function(post) {
    meta.posts.push({
      title: post.title,
      url: encodeURI(post.permalink),
      date: post.updated.toDate().toISOString() || post.date.toDate().toISOString()
    })
  })
  return {path: 'meta.json', data: JSON.stringify(meta)}
})
```

**Comment by i-am-phi** [comment]
@mh61503891 - where do you place the meta.js file?

**Comment by i-am-phi** [comment]
I determined that the meta.js file should be placed in a "scripts' folder within the theme. 

Through this, I am also realizing the incredible power and flexibility of the Hexo platform.

**Comment by timnew** [comment]
Issue has been fixed
