### ISSUE TITLE
Url for Tags	

### ISSUE THREAD

**Issue by sundevilyang** [timnew/hexo-generator-atom-markdown-writer-meta#2]
你好，

好像现在这个插件还不支持 3.X，等你update。

想问一个问题，Url for Tags   这里的Url是我的域名，还是应该是github page呢？
1. http://sundevilyang.github.io/tags.json
2. http://sundevilyang.com/tags.json

应该是1还是2？

谢谢

**Comment by z-caterpillar** [comment]
@sundevilyang 
3.X版本的我已经修改了，hexo:3.2.2测试可用。

#3

**Comment by timnew** [comment]
Issue has been solved
